package main

import (
	"flag"
	"fmt"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

const version = "1.0.0"

func main() {
	showVersion := flag.Bool("version", false, "print the version and exit")
	flag.Parse()
	if *showVersion {
		fmt.Printf("protoc-gen-go-gin %v\n", version)
		return
	}

	var flags flag.FlagSet

	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

const (
	httpPackage        = protogen.GoImportPath("net/http")
	ginPackage         = protogen.GoImportPath("github.com/gin-gonic/gin")
	ginBingdingPackage = protogen.GoImportPath("github.com/gin-gonic/gin/binding")
	grpcPackage        = protogen.GoImportPath("google.golang.org/grpc")
)

// generateFile generates a _grpc.pb.go file containing gRPC service definitions.
func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_gin.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-gin. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-go-gin v", version)
	g.P("// - protoc             ", protocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	generateFileContent(gen, file, g)
	return g
}

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

// generateFileContent generates the gRPC service definitions, excluding the package statement.
func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	if len(file.Services) == 0 {
		return
	}

	for _, service := range file.Services {
		genService(gen, file, g, service)
	}
}

func genService(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, service *protogen.Service) {
	svr := strings.ToLower(service.GoName[:1]) + service.GoName[1:]
	g.P("var ", svr, "Gin", " ", service.GoName, "Server")

	for _, method := range service.Methods {
		g.P("func ", unexport(method.GoName), "G(c *", ginPackage.Ident("Context"), ") {")
		g.P("a := &", method.Input.GoIdent, "{}")
		g.P(`err := c.BindWith(a,`, ginBingdingPackage.Ident(`Default(c.Request.Method, c.Request.Header.Get("Content-Type")))`))
		g.P(`if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
			 }`)

		g.P("resp, err := ", svr, "Gin.", method.GoName, "(c, a)")
		g.P(`if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
			 }`)
		g.P("c.JSON(", httpPackage.Ident("StatusOK"), ", resp)")

		g.P("}")
	}

	g.P("func RegisterGin(e *", ginPackage.Ident("Engine"), ", svr ", service.GoName, "Server){")
	g.P(svr, "Gin = svr")
	for _, method := range service.Methods {
		path := strconv.Quote(fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name()))
		g.P("e.POST(", path, ",", unexport(method.GoName), "G)")
	}
	g.P("}")

}

func unexport(s string) string { return strings.ToLower(s[:1]) + s[1:] }
